// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numTest = Integer.parseInt(args[0]);
		double rnd = Math.random();
		double above = 0;
		double below = 0;
		for (int i = 0; i < numTest ; i++){
			if (rnd <= 0.5) {
				below++;
			} else if (rnd > 0.5) {
				above++;
			}
			rnd = Math.random();
		}
		System.out.println("> 0.5 : " + (int)above + " times");
		System.out.println("<= 0.5 : " + (int)below + " times");
		if (above != 0 && below != 0) {
			System.out.println("ratio : " + above/below  + " times");
		}
	}
}
